name: orihime-cleanup

on:
  pull_request:
    types: [closed]

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: srinivasan-sundaresan95/orihime/actions/cleanup@v1
        with:
          write_url: ${{ secrets.ORIHIME_WRITE_URL }}
          branch: ${{ github.head_ref }}
