name: orihime-index

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  index-pr:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: srinivasan-sundaresan95/orihime/actions/index@v1
        with:
          write_url: ${{ secrets.ORIHIME_WRITE_URL }}
          branch: ${{ github.head_ref }}

  index-master:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: srinivasan-sundaresan95/orihime/actions/index@v1
        with:
          write_url: ${{ secrets.ORIHIME_WRITE_URL }}
          branch: master
